### ISSUE TITLE
flex: fatal internal error, freopen(headerfilename) failed

### ISSUE THREAD

**Issue by bigyanse** [ydrojd/rvasm#1]
## Expected Behavior
It should compile without errors.

## Actual Behavior
![Screenshot_20241130221752](https://github.com/user-attachments/assets/d2401ee8-1dc0-4532-a257-9aa173d6f958)

## Steps to Reproduce the Problem

  1. mkdir build
  2. cd build
  3. cmake ..
  4. make

**Comment by ydrojd** [comment]
I made some changes to CMakeLists.txt and it should work now.

**Comment by bigyanse** [comment]
`F.h` file could not still be included due to path issue. I can make it work changing the relative include path of the `F.h`, but I think you should use absolute path instead, so it works regardless of where you build.

![image](https://github.com/user-attachments/assets/63dd9169-913e-46aa-b68b-a978692c008f)
